from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class SystemProfile:
    system: str
    rbf: str
    setname: str
    file_delay: int
    file_index: int
    file_type: str
    exts: tuple[str, ...]
    prefix_in_core: str = "nointro"
    slots: tuple["Slot", ...] | None = None


@dataclass(frozen=True)
class FileEntry:
    delay: int
    file_type: str
    index: int
    path: str | None = None


@dataclass(frozen=True)
class Slot:
    exts: tuple[str, ...]
    files: tuple[FileEntry, ...]


PROFILES: dict[str, SystemProfile] = {
    "amiga": SystemProfile(
        system="amiga",
        rbf="_Computer/Minimig",
        setname="Amiga",
        file_delay=1,
        file_index=0,
        file_type="f",
        exts=(".adf",),
        prefix_in_core="nointro",
    ),
    "arcadia": SystemProfile(
        system="arcadia",
        rbf="_Console/Arcadia",
        setname="Arcadia",
        file_delay=1,
        file_index=1,
        file_type="f",
        exts=(".bin",),
        prefix_in_core="nointro",
    ),
    "avision": SystemProfile(
        system="avision",
        rbf="_Console/AdventureVision",
        setname="AVision",
        file_delay=1,
        file_index=1,
        file_type="f",
        exts=(".bin",),
        prefix_in_core="nointro",
    ),
    "astrocade": SystemProfile(
        system="astrocade",
        rbf="_Console/Astrocade",
        setname="Astrocade",
        file_delay=1,
        file_index=1,
        file_type="f",
        exts=(".bin",),
        prefix_in_core="nointro",
    ),
    "atari2600": SystemProfile(
        system="atari2600",
        rbf="_Console/Atari7800",
        setname="ATARI2600",
        file_delay=1,
        file_index=1,
        file_type="f",
        exts=(".a78", ".a26", ".bin"),
        prefix_in_core="nointro",
    ),
    "atari5200": SystemProfile(
        system="atari5200",
        rbf="_Console/Atari5200",
        setname="ATARI5200",
        file_delay=1,
        file_index=1,
        file_type="s",
        exts=(".car", ".a52", ".bin", ".rom"),
        prefix_in_core="nointro",
    ),
    "atari7800": SystemProfile(
        system="atari7800",
        rbf="_Console/Atari7800",
        setname="ATARI7800",
        file_delay=1,
        file_index=1,
        file_type="f",
        exts=(".a78", ".a26", ".bin"),
        prefix_in_core="nointro",
    ),
    "atarilynx": SystemProfile(
        system="atarilynx",
        rbf="_Console/AtariLynx",
        setname="AtariLynx",
        file_delay=1,
        file_index=0,
        file_type="f",
        exts=(".lnx",),
        prefix_in_core="nointro",
    ),
    "c64": SystemProfile(
        system="c64",
        rbf="_Computer/C64",
        setname="C64",
        file_delay=1,
        file_index=1,
        file_type="f",
        exts=(".prg", ".crt", ".reu", ".tap", ".d64"),
        prefix_in_core="nointro",
        slots=(
            Slot(
                exts=(".d64",),
                files=(
                    FileEntry(delay=1, file_type="s", index=0),
                    FileEntry(delay=0, file_type="f", index=1, path="autorun.prg"),
                ),
            ),
            Slot(
                exts=(".prg", ".crt", ".reu", ".tap"),
                files=(FileEntry(delay=1, file_type="f", index=1),),
            ),
        ),
    ),
    "channelf": SystemProfile(
        system="channelf",
        rbf="_Console/ChannelF",
        setname="ChannelF",
        file_delay=1,
        file_index=1,
        file_type="f",
        exts=(".rom", ".bin"),
        prefix_in_core="nointro",
    ),
    "coleco": SystemProfile(
        system="coleco",
        rbf="_Console/ColecoVision",
        setname="Coleco",
        file_delay=1,
        file_index=1,
        file_type="f",
        exts=(".col", ".bin", ".rom", ".sg"),
        prefix_in_core="nointro",
        slots=(
            Slot(
                exts=(".col", ".bin", ".rom"),
                files=(FileEntry(delay=1, file_type="f", index=1),),
            ),
            Slot(
                exts=(".sg",),
                files=(FileEntry(delay=1, file_type="f", index=2),),
            ),
        ),
    ),
    "creativision": SystemProfile(
        system="creativision",
        rbf="_Console/CreatiVision",
        setname="CreatiVision",
        file_delay=1,
        file_index=1,
        file_type="f",
        exts=(".rom", ".bin"),
        prefix_in_core="nointro",
    ),
    "gameboy2p": SystemProfile(
        system="gameboy2p",
        rbf="_Console/Gameboy2P",
        setname="GAMEBOY2P",
        file_delay=2,
        file_index=1,
        file_type="f",
        exts=(".gb", ".gbc"),
        prefix_in_core="nointro",
    ),
    "gameboy": SystemProfile(
        system="gameboy",
        rbf="_Console/Gameboy",
        setname="GAMEBOY",
        file_delay=2,
        file_index=1,
        file_type="f",
        exts=(".gb", ".gbc"),
        prefix_in_core="nointro",
    ),
    "gbc": SystemProfile(
        system="gbc",
        rbf="_Console/Gameboy",
        setname="GBC",
        file_delay=2,
        file_index=1,
        file_type="f",
        exts=(".gbc",),
        prefix_in_core="nointro",
    ),
    "gamate": SystemProfile(
        system="gamate",
        rbf="_Console/Gamate",
        setname="Gamate",
        file_delay=1,
        file_index=1,
        file_type="f",
        exts=(".bin",),
        prefix_in_core="nointro",
    ),
    "gamenwatch": SystemProfile(
        system="gamenwatch",
        rbf="_Console/GnW",
        setname="GameNWatch",
        file_delay=1,
        file_index=1,
        file_type="f",
        exts=(".bin",),
        prefix_in_core="nointro",
    ),
    "gamegear": SystemProfile(
        system="gamegear",
        rbf="_Console/SMS",
        setname="GameGear",
        file_delay=1,
        file_index=2,
        file_type="f",
        exts=(".gg",),
        prefix_in_core="nointro",
    ),
    "gba2p": SystemProfile(
        system="gba2p",
        rbf="_Console/GBA2P",
        setname="GBA2P",
        file_delay=2,
        file_index=0,
        file_type="f",
        exts=(".gba",),
        prefix_in_core="nointro",
    ),
    "gba": SystemProfile(
        system="gba",
        rbf="_Console/GBA",
        setname="GBA",
        file_delay=2,
        file_index=1,
        file_type="f",
        exts=(".gba",),
        prefix_in_core="nointro",
    ),
    "megadrive": SystemProfile(
        system="megadrive",
        rbf="_Console/MegaDrive",
        setname="MegaDrive",
        file_delay=1,
        file_index=1,
        file_type="f",
        exts=(".bin", ".gen", ".md"),
        prefix_in_core="nointro",
    ),
    "genesis": SystemProfile(
        system="genesis",
        rbf="_Console/Genesis",
        setname="Genesis",
        file_delay=1,
        file_index=1,
        file_type="f",
        exts=(".bin", ".gen", ".md"),
        prefix_in_core="nointro",
    ),
    "intellivision": SystemProfile(
        system="intellivision",
        rbf="_Console/Intellivision",
        setname="Intellivision",
        file_delay=1,
        file_index=1,
        file_type="f",
        exts=(".rom", ".int", ".bin"),
        prefix_in_core="nointro",
    ),
    "megacd": SystemProfile(
        system="megacd",
        rbf="_Console/MegaCD",
        setname="MegaCD",
        file_delay=1,
        file_index=0,
        file_type="s",
        exts=(".cue", ".chd"),
        prefix_in_core="nointro",
    ),
    "n64": SystemProfile(
        system="n64",
        rbf="_Console/N64",
        setname="N64",
        file_delay=1,
        file_index=1,
        file_type="f",
        exts=(".n64", ".z64"),
        prefix_in_core="nointro",
    ),
    "neogeocd": SystemProfile(
        system="neogeocd",
        rbf="_Console/NeoGeo",
        setname="NeoGeo-CD",
        file_delay=1,
        file_index=1,
        file_type="s",
        exts=(".cue", ".chd"),
        prefix_in_core="nointro",
    ),
    "neogeo": SystemProfile(
        system="neogeo",
        rbf="_Console/NeoGeo",
        setname="NeoGeo",
        file_delay=1,
        file_index=1,
        file_type="f",
        exts=(".neo",),
        prefix_in_core="nointro",
    ),
    "nes": SystemProfile(
        system="nes",
        rbf="_Console/NES",
        setname="NES",
        file_delay=2,
        file_index=1,
        file_type="f",
        exts=(".nes", ".fds", ".nsf"),
        prefix_in_core="nointro",
    ),
    "odyssey2": SystemProfile(
        system="odyssey2",
        rbf="_Console/Odyssey2",
        setname="ODYSSEY2",
        file_delay=1,
        file_index=1,
        file_type="f",
        exts=(".bin",),
        prefix_in_core="nointro",
    ),
    "psx": SystemProfile(
        system="psx",
        rbf="_Console/PSX",
        setname="PSX",
        file_delay=1,
        file_index=1,
        file_type="s",
        exts=(".cue", ".chd"),
        prefix_in_core="nointro",
    ),
    "pocketchallengev2": SystemProfile(
        system="pocketchallengev2",
        rbf="_Console/WonderSwan",
        setname="PocketChallengeV2",
        file_delay=1,
        file_index=1,
        file_type="f",
        exts=(".pc2",),
        prefix_in_core="nointro",
    ),
    "pokemonmini": SystemProfile(
        system="pokemonmini",
        rbf="_Console/PokemonMini",
        setname="PokemonMini",
        file_delay=1,
        file_index=1,
        file_type="f",
        exts=(".min",),
        prefix_in_core="nointro",
    ),
    "saturn": SystemProfile(
        system="saturn",
        rbf="_Console/Saturn",
        setname="Saturn",
        file_delay=1,
        file_index=0,
        file_type="s",
        exts=(".cue", ".chd"),
        prefix_in_core="nointro",
    ),
    "s32x": SystemProfile(
        system="s32x",
        rbf="_Console/S32X",
        setname="S32X",
        file_delay=1,
        file_index=1,
        file_type="f",
        exts=(".32x",),
        prefix_in_core="nointro",
    ),
    "sg1000": SystemProfile(
        system="sg1000",
        rbf="_Console/ColecoVision",
        setname="SG1000",
        file_delay=1,
        file_index=2,
        file_type="f",
        exts=(".sg",),
        prefix_in_core="nointro",
    ),
    "sgb": SystemProfile(
        system="sgb",
        rbf="_Console/SGB",
        setname="SGB",
        file_delay=1,
        file_index=1,
        file_type="f",
        exts=(".gb", ".gbc"),
        prefix_in_core="nointro",
    ),
    "sms": SystemProfile(
        system="sms",
        rbf="_Console/SMS",
        setname="SMS",
        file_delay=1,
        file_index=1,
        file_type="f",
        exts=(".sms", ".sg", ".gg"),
        prefix_in_core="nointro",
        slots=(
            Slot(
                exts=(".sms", ".sg"),
                files=(FileEntry(delay=1, file_type="f", index=1),),
            ),
            Slot(
                exts=(".gg",),
                files=(FileEntry(delay=1, file_type="f", index=2),),
            ),
        ),
    ),
    "snes": SystemProfile(
        system="snes",
        rbf="_Console/SNES",
        setname="SNES",
        file_delay=2,
        file_index=0,
        file_type="f",
        exts=(".sfc", ".smc", ".bin", ".bs"),
        prefix_in_core="nointro",
    ),
    "supervision": SystemProfile(
        system="supervision",
        rbf="_Console/SuperVision",
        setname="SuperVision",
        file_delay=1,
        file_index=1,
        file_type="s",
        exts=(".bin", ".sv"),
        prefix_in_core="nointro",
    ),
    "tgfx16cd": SystemProfile(
        system="tgfx16cd",
        rbf="_Console/TurboGrafx16",
        setname="TGFX16-CD",
        file_delay=1,
        file_index=0,
        file_type="s",
        exts=(".cue", ".chd"),
        prefix_in_core="nointro",
    ),
    "tgfx16": SystemProfile(
        system="tgfx16",
        rbf="_Console/TurboGrafx16",
        setname="TGFX16",
        file_delay=1,
        file_index=0,
        file_type="f",
        exts=(".pce", ".bin"),
        prefix_in_core="nointro",
    ),
    "vc4000": SystemProfile(
        system="vc4000",
        rbf="_Console/VC4000",
        setname="VC4000",
        file_delay=1,
        file_index=1,
        file_type="f",
        exts=(".bin",),
        prefix_in_core="nointro",
    ),
    "vectrex": SystemProfile(
        system="vectrex",
        rbf="_Console/Vectrex",
        setname="VECTREX",
        file_delay=1,
        file_index=1,
        file_type="f",
        exts=(".ovr", ".vec", ".bin", ".rom"),
        prefix_in_core="nointro",
    ),
    "wonderswan": SystemProfile(
        system="wonderswan",
        rbf="_Console/WonderSwan",
        setname="WonderSwan",
        file_delay=1,
        file_index=1,
        file_type="f",
        exts=(".wsc", ".ws"),
        prefix_in_core="nointro",
    ),
    "wonderswancolor": SystemProfile(
        system="wonderswancolor",
        rbf="_Console/WonderSwan",
        setname="WonderSwanColor",
        file_delay=1,
        file_index=1,
        file_type="f",
        exts=(".wsc",),
        prefix_in_core="nointro",
    ),
}
